In [1]:
import pandas as pd
import torch
import tensorflow as tf
import numpy as np

In [2]:
data = pd.read_csv(r'../Dataset/Datathon-COVID-Completed.csv')

In [27]:
data.head(50)

,Date,Colombo - Total,Gampaha - Total,Kalatura - Total,Jaffna - Total,Mannar - Total,Kilinochchi,Mullaitivu,Vavuniya - Total,Puttalam - Total,...,Matara - Total,Galle - Total,Kandakadu Rehabilitation Center - Total,Naval Base - Welisara - Total,Overseas Arrivals (Quarantine Centers) - Total,Senapura Rehabilitation Center - Total,Unspecified - Total,Godagama - Total,Kendalanda - Total,Total_Island
0,1/27/20,0,1,0,0,0,NaN,NaN,0,0,...,0,0,0,0,0,0,0,0,0,1.0
1,1/28/20,0,0,0,0,0,NaN,NaN,0,0,...,0,0,0,0,0,0,0,0,0,0.0
2,1/29/20,0,0,0,0,0,NaN,NaN,0,0,...,0,0,0,0,0,0,0,0,0,0.0
3,1/30/20,0,0,0,0,0,NaN,NaN,0,0,...,0,0,0,0,0,0,0,0,0,0.0
4,1/31/20,0,0,0,0,0,NaN,NaN,0,0,...,0,0,0,0,0,0,0,0,0,0.0
5,2/1/20,0,0,0,0,0,NaN,NaN,0,0,...,0,0,0,0,0,0,0,0,0,0.0
6,2/2/20,0,0,0,0,0,NaN,NaN,0,0,...,0,0,0,0,0,0,0,0,0,0.0
7,2/3/20,0,0,0,0,0,NaN,NaN,0,0,...,0,0,0,0,0,0,0,0,0,0.0
8,2/4/20,0,0,0,0,0,NaN,NaN,0,0,...,0,0,0,0,0,0,0,0,0,0.0
9,2/5/20,0,0,0,0,0,NaN,NaN,0,0,...,0,0,0,0,0,0,0,0,0,0.0
10,2/6/20,0,0,0,0,0,NaN,NaN,0,0,...,0,0,0,0,0,0,0,0,0,0.0
11,2/7/20,0,0,0,0,0,NaN,NaN,0,0,...,0,0,0,0,0,0,0,0,0,0.0
12,2/8/20,0,0,0,0,0,NaN,NaN,0,0,...,0,0,0,0,0,0,0,0,0,0.0
13,2/9/20,0,0,0,0,0,NaN,NaN,0,0,...,0,0,0,0,0,0,0,0,0,0.0
14,2/10/20,0,0,0,0,0,NaN,NaN,0,0,...,0,0,0,0,0,0,0,0,0,0.0
15,2/11/20,0,0,0,0,0,NaN,NaN,0,0,...,0,0,0,0,0,0,0,0,0,0.0
16,2/12/20,0,0,0,0,0,NaN,NaN,0,0,...,0,0,0,0,0,0,0,0,0,0.0
17,2/13/20,0,0,0,0,0,NaN,NaN,0,0,...,0,0,0,0,0,0,0,0,0,0.0
18,2/14/20,0,0,0,0,0,NaN,NaN,0,0,...,0,0,0,0,0,0,0,0,0,0.0
19,2/15/20,0,0,0,0,0,NaN,NaN,0,0,...,0,0,0,0,0,0,0,0,0,0.0
20,2/16/20,0,0,0,0,0,NaN,NaN,0,0,...,0,0,0,0,0,0,0,0,0,0.0
21,2/17/20,0,0,0,0,0,NaN,NaN,0,0,...,0,0,0,0,0,0,0,0,0,0.0
22,2/18/20,0,0,0,0,0,NaN,NaN,0,0,...,0,0,0,0,0,0,0,0,0,0.0
23,2/19/20,0,0,0,0,0,NaN,NaN,0,0,...,0,0,0,0,0,0,0,0,0,0.0
24,2/20/20,0,0,0,0,0,NaN,NaN,0,0,...,0,0,0,0,0,0,0,0,0,0.0
25,2/21/20,0,0,0,0,0,NaN,NaN,0,0,...,0,0,0,0,0,0,0,0,0,0.0
26,2/22/20,0,0,0,0,0,NaN,NaN,0,0,...,0,0,0,0,0,0,0,0,0,0.0
27,2/23/20,0,0,0,0,0,NaN,NaN,0,0,...,0,0,0,0,0,0,0,0,0,0.0
28,2/24/20,0,0,0,0,0,NaN,NaN,0,0,...,0,0,0,0,0,0,0,0,0,0.0
29,2/25/20,0,0,0,0,0,NaN,NaN,0,0,...,0,0,0,0,0,0,0,0,0,0.0
30,2/26/20,0,0,0,0,0,NaN,NaN,0,0,...,0,0,0,0,0,0,0,0,0,0.0
31,2/27/20,0,0,0,0,0,NaN,NaN,0,0,...,0,0,0,0,0,0,0,0,0,0.0
32,2/28/20,0,0,0,0,0,NaN,NaN,0,0,...,0,0,0,0,0,0,0,0,0,0.0
33,2/29/20,0,0,0,0,0,NaN,NaN,0,0,...,0,0,0,0,0,0,0,0,0,0.0
34,3/1/20,0,0,0,0,0,NaN,NaN,0,0,...,0,0,0,0,0,0,0,0,0,0.0
35,3/2/20,0,0,0,0,0,NaN,NaN,0,0,...,0,0,0,0,0,0,0,0,0,0.0
36,3/3/20,0,0,0,0,0,NaN,NaN,0,0,...,0,0,0,0,0,0,0,0,0,0.0
37,3/4/20,0,0,0,0,0,NaN,NaN,0,0,...,0,0,0,0,0,0,0,0,0,0.0
38,3/5/20,0,0,0,0,0,NaN,NaN,0,0,...,0,0,0,0,0,0,0,0,0,0.0
39,3/6/20,0,0,0,0,0,NaN,NaN,0,0,...,0,0,0,0,0,0,0,0,0,0.0
40,3/7/20,0,0,0,0,0,NaN,NaN,0,0,...,0,0,0,0,0,0,0,0,0,0.0
41,3/8/20,0,0,0,0,0,NaN,NaN,0,0,...,0,0,0,0,0,0,0,0,0,0.0
42,3/9/20,0,0,0,0,0,NaN,NaN,0,0,...,0,0,0,0,0,0,0,0,0,0.0
43,3/10/20,1,0,0,0,0,NaN,NaN,0,0,...,0,0,0,0,0,0,0,0,0,1.0
44,3/11/20,0,0,0,0,0,NaN,NaN,0,0,...,0,0,0,0,0,0,0,0,0,0.0
45,3/12/20,1,0,0,0,0,NaN,NaN,0,0,...,0,0,0,0,0,0,0,0,0,1.0
46,3/13/20,1,1,0,0,0,NaN,NaN,0,0,...,0,0,0,0,0,0,0,0,0,3.0
47,3/14/20,3,0,0,0,0,NaN,NaN,0,1,...,0,1,0,0,0,0,0,0,0,5.0
48,3/15/20,4,0,0,0,0,NaN,NaN,0,0,...,0,0,0,0,0,0,0,0,0,7.0
49,3/16/20,0,0,0,0,0,NaN,NaN,0,0,...,0,0,0,0,0,0,0,0,0,10.0

In [4]:
island_data = data.iloc[42:277, -1]

In [5]:
island_data.head(50)

42     0.0
43     1.0
44     0.0
45     1.0
46     3.0
47     5.0
48     7.0
49    10.0
50    15.0
51     9.0
52     7.0
53    13.0
54    10.0
55     0.0
56    15.0
57     5.0
58     0.0
59     4.0
60     0.0
61     7.0
62     4.0
63     5.0
64    21.0
65     3.0
66     5.0
67     8.0
68     7.0
69    10.0
70     2.0
71     7.0
72     4.0
73     1.0
74     0.0
75     9.0
76    11.0
77     8.0
78    15.0
79     5.0
80     0.0
81     6.0
82    10.0
83    17.0
84    33.0
85     6.0
86    20.0
87     5.0
88    41.0
89    38.0
90    25.0
91    17.0
Name: Total_Island, dtype: float64

In [6]:
## splitting data

In [7]:
test_data_size = 15
train_data = island_data[:-test_data_size]
test_data = island_data[-test_data_size:]

In [8]:
train_data.shape

(220,)

In [9]:
train_data

42       0.0
43       1.0
44       0.0
45       1.0
46       3.0
       ...
257    105.0
258    124.0
259     92.0
260    194.0
261    132.0
Name: Total_Island, Length: 220, dtype: float64

In [10]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

In [11]:
scaler = scaler.fit(np.expand_dims(train_data, axis = 1))
scaled_train = scaler.transform(np.expand_dims(train_data, axis = 1))
scaled_test = scaler.transform(np.expand_dims(test_data, axis = 1))

In [12]:
scaled_train

array([[0.        ],
       [0.00192678],
       [0.        ],
       [0.00192678],
       [0.00578035],
       [0.00963391],
       [0.01348748],
       [0.01926782],
       [0.02890173],
       [0.01734104],
       [0.01348748],
       [0.02504817],
       [0.01926782],
       [0.        ],
       [0.02890173],
       [0.00963391],
       [0.        ],
       [0.00770713],
       [0.        ],
       [0.01348748],
       [0.00770713],
       [0.00963391],
       [0.04046243],
       [0.00578035],
       [0.00963391],
       [0.01541426],
       [0.01348748],
       [0.01926782],
       [0.00385356],
       [0.01348748],
       [0.00770713],
       [0.00192678],
       [0.        ],
       [0.01734104],
       [0.02119461],
       [0.01541426],
       [0.02890173],
       [0.00963391],
       [0.        ],
       [0.01156069],
       [0.01926782],
       [0.0327553 ],
       [0.06358382],
       [0.01156069],
       [0.03853565],
       [0.00963391],
       [0.07899807],
       [0.07321773],
       [0.04816956],
       [0.0327553 ],
       [0.03082852],
       [0.01926782],
       [0.01348748],
       [0.01541426],
       [0.02504817],
       [0.02504817],
       [0.06358382],
       [0.03660886],
       [0.05780347],
       [0.05202312],
       [0.02119461],
       [0.02312139],
       [0.03082852],
       [0.01156069],
       [0.03853565],
       [0.05009634],
       [0.01926782],
       [0.01926782],
       [0.04816956],
       [0.00385356],
       [0.00192678],
       [0.        ],
       [0.00192678],
       [0.02890173],
       [0.        ],
       [0.00385356],
       [0.09633911],
       [0.07899807],
       [0.24470135],
       [0.18689788],
       [0.06936416],
       [0.02119461],
       [0.07129094],
       [0.01734104],
       [0.01541426],
       [0.06358382],
       [0.06743738],
       [0.01156069],
       [0.00385356],
       [0.00770713],
       [0.04046243],
       [0.02312139],
       [0.00192678],
       [0.00385356],
       [0.        ],
       [0.00192678],
       [0.00578035],
       [0.        ],
       [0.02504817],
       [0.00770713],
       [0.01348748],
       [0.04431599],
       [0.00578035],
       [0.        ],
       [0.        ],
       [0.00192678],
       [0.07707129],
       [0.01348748],
       [0.00578035],
       [0.00770713],
       [0.03660886],
       [0.00770713],
       [0.00963391],
       [0.00963391],
       [0.01348748],
       [0.02312139],
       [0.00578035],
       [0.00963391],
       [0.00385356],
       [0.00192678],
       [0.00192678],
       [0.02890173],
       [0.11753372],
       [0.57418112],
       [0.10982659],
       [0.20423892],
       [0.05587669],
       [0.03853565],
       [0.01541426],
       [0.02504817],
       [0.01926782],
       [0.01348748],
       [0.03853565],
       [0.01156069],
       [0.        ],
       [0.04238921],
       [0.00192678],
       [0.02119461],
       [0.01156069],
       [0.02312139],
       [0.04431599],
       [0.00963391],
       [0.00192678],
       [0.00578035],
       [0.00192678],
       [0.        ],
       [0.01541426],
       [0.00963391],
       [0.01156069],
       [0.00963391],
       [0.        ],
       [0.        ],
       [0.00385356],
       [0.00578035],
       [0.05202312],
       [0.01734104],
       [0.00192678],
       [0.00192678],
       [0.00770713],
       [0.00770713],
       [0.00578035],
       [0.01348748],
       [0.00385356],
       [0.        ],
       [0.03082852],
       [0.04431599],
       [0.01156069],
       [0.01156069],
       [0.01156069],
       [0.02312139],
       [0.02504817],
       [0.00385356],
       [0.00578035],
       [0.01156069],
       [0.0327553 ],
       [0.07129094],
       [0.08092486],
       [0.01734104],
       [0.01926782],
       [0.00770713],
       [0.01156069],
       [0.00385356],
       [0.        ],
       [0.0327553 ],
       [0.01348748],
       [0.01541426],
       [0.02697495],
       [0.05009634],
       [0.07514451],
       [0.0539499 ],
       [0.01734104],
       [0.        ],
       [0.00963391],
       [0.00963391],
       [0.00385356],
       [0.00770713],
       [0.02312139],
       [0.02697495],
       [0.02119461],
       [0.01734104],
       [0.02312139],
       [0.00770713],
       [0.02119461],
       [0.00578035],
       [0.02119461],
       [0.01156069],
       [0.00385356],
       [0.01156069],
       [0.01541426],
       [0.14450867],
       [0.50481696],
       [1.        ],
       [0.39884393],
       [0.05587669],
       [0.06743738],
       [0.20231214],
       [0.238921  ],
       [0.17726397],
       [0.37379576],
       [0.25433526]])

In [13]:
## creating sequences

In [16]:
def create_sequences(df, seq_length):
    xs = []
    ys = []
    
    for i in range(len(df) - seq_length - 1):
        x = df[i:(i+seq_length)]
        y = df[i+seq_length]
        xs.append(x)
        ys.append(y)
    return np.array(xs), np.array(ys)

In [17]:
len(island_data)

235

In [19]:
seq_length = 15
X_train, y_train = create_sequences(scaled_train, seq_length)
X_test, y_test = create_sequences(scaled_test, seq_length)

X_train = torch.from_numpy(X_train).float()
X_test = torch.from_numpy(X_test).float()
y_train = torch.from_numpy(y_train).float()
y_test = torch.from_numpy(y_test).float()

In [24]:
print(X_train[1])
print(y_train[0])

tensor([[0.0019],
        [0.0000],
        [0.0019],
        [0.0058],
        [0.0096],
        [0.0135],
        [0.0193],
        [0.0289],
        [0.0173],
        [0.0135],
        [0.0250],
        [0.0193],
        [0.0000],
        [0.0289],
        [0.0096]])
tensor([0.0096])

In [25]:
##Creating the model

In [29]:
import torch.nn as nn
class SeriesPredictor(nn.Module):
    def __init__(self, n_features, n_hidden, seq_len, n_layers = 2):
        super(SeriesPredictor, self).__init__()
        
        self.n_hidden = n_hidden
        self.seq_len = seq_len
        self.n_layers = n_layers
        
        self.lstm = nn.LSTM(
            input_size = n_features,
            hidden_size = n_hidden,
            num_layers = n_layers,
            dropout = 0.2)
        
        self.linear = nn.Linear(in_features = n_hidden, out_features = 1)
        
    def reset_hidden_state(self):
        self.hidden = (
            torch.zeros(self.n_layers, self.seq_len, self.n_hidden),
            torch.zeros(self.n_layers, self.seq_len, self.n_hidden)
        )
        
    def forward(self, sequences):
        lstm_out, self.hidden = self.lstm(
            sequences.view(len(sequences), self.seq_len, -1),
            self.hidden)
        last_time_step = \
            lstm_out.view(self.seq_len, len(sequences), self.n_hidden)[-1]
        y_pred = self.linear(last_time_step)
        return y_pred

In [31]:
model = SeriesPredictor(
    n_features = 1,
    n_hidden = 50,
    seq_len = seq_length,
    n_layers = 2)

In [35]:
def train_model(
    model,
    train_data,
    train_labels,
    test_data = None,
    test_labels = None):
    
    loss_fn = torch.nn.MSELoss(reduction = 'sum')
    optimizer = torch.optim.Adam(model.parameters(), lr = 1e-3)
    num_epochs = 20
    
    train_hist = np.zeros(num_epochs)
    test_hist = np.zeros(num_epochs)
    
    for t in range(num_epochs):
        model.reset_hidden_state()
        y_pred = model(X_train)
        loss = loss_fn(y_pred.float(), y_train)
        
        if test_data is not None:
            with torch.no_grad():
                y_test_pred = model(X_test)
                test_loss = loss_fn(y_test_pred.float(), y_test)
            test_hist[t] = test_loss.item()
            
            print(f'Epoch {t} train loss: {loss.item()} test loss: {test_loss.item()}')
            
        train_hist[t] = loss.item()
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        
    return model.eval(), train_hist, test_hist

In [36]:
with torch.no_grad():
    test_seq = X_test[:1]
    preds = []
    for i in range(len(X_test)):
        y_test_pred = model(test_seq)
        pred = torch.flatten(y_test_pred).item()
        preds.append(pred)
        
        new_seq = test_seq.numpy().flatten()
        new_seq = np.append(new_seq, [pred])
        new_seq = new_seq[1:]
        test_seq = torch.as_tensor(new_seq).view(1, seq_length, 1).flaot()

In [37]:
train = train_model(model, X_train, X_test, y_train, y_test)

RuntimeError: cannot reshape tensor of 0 elements into shape [0, 15, -1] because the unspecified dimension size -1 can be any value and is ambiguous